"""empty message

Revision ID: 72d4dd7e2f9c
Revises: b00dbca81e15
Create Date: 2022-05-16 12:38:45.842583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d4dd7e2f9c'
down_revision = 'b00dbca81e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('tokenExpiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'tokenExpiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
